# -*- coding: utf-8 -*-
"""MiniProject.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qyvztyULa1EyTQ1oe8yU7Yv-e0Jm8cyB

**Email Slicer**
 The tool that will take an email address as input and split it to produce the username and the domain name associated with it. The email must be divided into two strings by using ‘@’ as the separator.
"""

email = input("Enter Your Email: ").strip()
username = email[:email.index('@')]
domain = email[email.index('@') + 1:]
print(f"Your username is {username} \n domain is {domain}")